""" added user images problem and stars

Revision ID: 29da748e0fe3
Revises: 232d45cc77c4
Create Date: 2024-10-03 19:35:17.098839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29da748e0fe3'
down_revision = '232d45cc77c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stars', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('stars')
        batch_op.drop_column('problem')

    # ### end Alembic commands ###
