""" added user name

Revision ID: 398b2025d3cf
Revises: 
Create Date: 2024-09-30 09:18:37.544927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398b2025d3cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_profile', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_profile_image_name', sa.String(length=50), nullable=True))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_profile_image_name')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('user_profile')

    # ### end Alembic commands ###
