"""added flasgs for verified

Revision ID: 942952baf006
Revises: 29da748e0fe3
Create Date: 2024-10-05 19:20:31.733070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942952baf006'
down_revision = '29da748e0fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_phone_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_phone_verified')
        batch_op.drop_column('user_email_verified')

    # ### end Alembic commands ###
